import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "../component/navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar />
                asdf
                <div>
                    <div className="text-center">
                        <h1 className="text-4xl">Judul</h1>
                    </div>
                    {children}
                </div>
                <p className="text-xs">
                    the quick brown fox jump over the lazy dog
                </p>
                <p className="text-sm">
                    the quick brown fox jump over the lazy dog
                </p>
                <p className="text-base">
                    the quick brown fox jump over the lazy dog
                </p>
                <p className="text-lg">
                    the quick brown fox jump over the lazy dog
                </p>
            </body>
        </html>
    );
}
